alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: test1
    match:
      path:
        prefix: /test1
  - component:
      name: website
    cors:
      allow_origins:
      - prefix: https://internal.example-app.com
    match:
      path:
        prefix: /
name: GWT-Open-Layers
region: nyc
services:
- environment_slug: go
  github:
    branch: main
    deploy_on_push: true
    repo: kyleteague/GWT-Open-Layers
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: api
  run_command: bin/api
  source_dir: /
