alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: website
    match:
      path:
        prefix: /
name: gwtopenlayers
region: nyc
services:
- environment_slug: JVM
  github:
    branch: main
    deploy_on_push: false
    repo: kyleteague/GWT-Open-Layers
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  run_command: java -jar webapp-runner.jar OpenLayers.war
